// THIS FILE IS ONLY FOR KEYS THAT ARE USED ON THE FRONTEND! DO NOT PUT ANYTHING HERE THAT SHOULDN'T BE PUBLIC
export default {
    INSTAGRAM_KEY: "IGQVJXck5ZAVFZAoaVJ5RWg1ajlBLWJpVW4waUx3RWpQS3pqVmNVblJ0VjdadDM1ZAFhhdWY4bjQxLUhfcEZAieXRxRG11RlVoQmg4Q21HSVluNktMNXVtOWR6VXdLcFl5MTJ3NlM3WVdFTlZAIaFQ1dUJRMgZDZD",
    GOOGLE_KEY: "AIzaSyAUZrwr1qS0UjHiUP4UAY6Dp_leoWLnAvA",
}